#!/usr/bin/env bash

##
# Copyright (c) 2016 Andrea Giammarchi
# 
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom
# the Software is furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
##

# grants access to the local screen
xhost +local:

if [ -f /usr/bin/xset ]; then
  xset s off -dpms
fi

# if there is a package json
if [ -f ~/app/package.json ]; then
  cd ~/app
  # in case there is no module folder yet
  if [ ! -d node_modules ]; then
    # create it and install possible dependencies
    mkdir node_modules
    npm install --production
  fi
  # launch the app via npm
  if [ -f /usr/bin/unclutter ]; then
    unclutter -idle 0 & sudo npm start
  else
    sudo npm start
  fi
  # NOTE: npm is unfortunately very slow in some case.
  #       It adds ~2 extra seconds to the bootstrap time.
else
  cd ~/
  # if there is no package, we assume it's a terminal session.
  # if package.json has been renamed to package.jsno/jsoff
  # it was an explicit reboot-to-shell operation
  # make it load normally next reboot
  if [ -f ~/app/package.jsno ]; then
    mv ~/app/package.jsno ~/app/package.json
  elif [ -f ~/app/package.jsoff ]; then
    mv ~/app/package.jsoff ~/app/package.json
  fi
  # launch any available terminal
  if [ -f /usr/bin/xterm ]; then
    xterm -maximized
  else
    weston-terminal --fullscreen
  fi
fi