#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

# BENJA OS

# logo
OS_LOGO=" 
  [1mIntel on x86_64[0;10m 
 [30m┌────────────────┐[0;10m
 [30m│[0;10m [1m[34m╔╗ ╔═╗╔╗╔ ╦╔═╗[0;10m [30m│[0;10m [2mBootable[0;10m
 [30m│[0;10m [1m[36m╠╩╗║╣ ║║║ ║╠═╣[0;10m [30m│[0;10m [2mElectron[0;10m
 [30m│[0;10m [1m[35m╚═╝╚═╝╝╚╝╚╝╩ ╩[0;10m [30m│[0;10m [2mNode JS App[0;10m
 [30m└────────────────┘[0;10m
  [2mhttps://benja.io[0;10m  0.3.0[0;10m"

# print a welcome message
echo -e "${OS_LOGO}
 "

# in case this is the first boot
if [ -f ~/need-wifi ]; then
  echo "$(tput bold)WiFi Configuration$(tput sgr0)"
  rm ~/need-wifi
  sudo wifi-setup
  sudo systemctl enable weston-compositor
fi


