#!/usr/bin/env bash

##
# Copyright (c) 2016 Andrea Giammarchi
# 
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom
# the Software is furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
##

installFromAUR() {
  local package="$1"
  cd /home/tmp-yaourt-install
  echo  " downloading ${package}"
  sudo -H -u nobody curl -LOs "https://aur.archlinux.org/cgit/aur.git/snapshot/${package}.tar.gz"
  echo " extracting ${package}"
  sudo -H -u nobody tar -xzf "${package}.tar.gz"
  echo " installing ${package}"
  cd "${package}"
  sudo -H -u nobody makepkg -Asc --needed --noconfirm
  sudo pacman -U --needed --noconfirm "${package}*.pkg.tar.xz"
  sync && sleep 1
  echo " $(tput bold)$(pacman -Q ${package})$(tput sgr0) successfully installed"
  cd -
}

sudo -H -u nobody mkdir -p /home/tmp-yaourt-install
echo "
$(tput bold)yaourt installer$(tput sgr0)
 "
echo  " installing dependencies"
sudo pacman -S --needed --noconfirm base-devel linux-headers git sudo diffstat chrpath wget cpio pv > /dev/null 2>&1
installFromAUR "package-query"
sync && sleep 1
installFromAUR "yaourt"
sync && sleep 1
sudo -H -u nobody rm -rf /home/tmp-yaourt-install
