#!/usr/bin/env bash

##
# Copyright (c) 2016 Andrea Giammarchi
# 
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom
# the Software is furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
##

# find out the current resolution
SIZE=$(xrandr | grep -o 'current\ \([0-9]\{1,\}\) x \([0-9]\{1,\}\)' | grep -o '\([0-9]\{1,\}\) x \([0-9]\{1,\}\)')
CURRENT_WIDTH=$(echo $SIZE | sed 's/ x.*$//')
CURRENT_HEIGHT=$(echo $SIZE | sed 's/^.*x //')
WIDTH=$CURRENT_WIDTH
HEIGHT=$CURRENT_HEIGHT

# in case the max resolution is not defined
if [ "$OS_MAX_RESOLUTION" = "" ]; then
  OS_MAX_RESOLUTION='1280x720'
fi

# grab MAX_WIDTH and MAX_HEIGHT
MAX_WIDTH=$(echo $OS_MAX_RESOLUTION | sed 's/[xX].*$//')
MAX_HEIGHT=$(echo $OS_MAX_RESOLUTION | sed 's/^.*[xX]//')

# if resolution is too big
# try to use a 720p one
# keeping rotation / ratio
if (( $CURRENT_WIDTH > $CURRENT_HEIGHT )) ; then
  if (( $CURRENT_HEIGHT > $MAX_HEIGHT )) ; then
    HEIGHT=$MAX_HEIGHT
    let "WIDTH=$CURRENT_WIDTH*$MAX_HEIGHT/$CURRENT_HEIGHT"
    WIDTH="$WIDTH"
  fi
else
  if (( $CURRENT_WIDTH > $MAX_HEIGHT )) ; then
    WIDTH=$MAX_HEIGHT
    let "HEIGHT=$CURRENT_HEIGHT*$MAX_HEIGHT/$CURRENT_WIDTH"
    HEIGHT="$HEIGHT"
  fi
fi

# echo "cur: ${CURRENT_WIDTH}x${CURRENT_HEIGHT}"
# echo "max: ${MAX_WIDTH}x${MAX_HEIGHT}"
# echo "now: ${WIDTH}x${HEIGHT}"

# setup new resolution
xrandr -s ${WIDTH}x${HEIGHT}

# avoid monitor goes to sleep
xset s off -dpms

# launch the app
weston --width=${WIDTH} --height=${HEIGHT}